---

- name: Deploy Application
  hosts: "{{ host }}"
  roles: 
    - www
  become: true
  become_user: www-data
  tags: [site-deployment,lamp-test]


- name: Deploy Application
  hosts: "{{ host }}"
  roles: 
    - db
  become: true
  become_user: www-data
  tags: [db]


