---
# - name: 'iquippo-build-creation'
- hosts: "{{ HOST }}"
  become: true
  become_user: varanet
  gather_facts: true
  become_method: su
  vars:
    app_path: /home/varanet/ansible
    app_dir: iquippo.com 
    server_file: ecosystem.config.js
  
  tasks:
    - stat:
        path: "{{ app_path }}"
      register: exist

    - name: create "{{ app_path }}" directory
      file: dest={{ app_path }} state=directory owner=varanet group=varanet mode=0700
      when: exist.stat.exists != True

    - git: 
        repo: http://atul:Atul9911@199.217.116.19/iquippo/iquippo.com.git
        dest: "{{ app_path }}/{{ app_dir }}"
        version: "{{ GIT_TAG }}"
        refspec: '+refs/heads/{{ GIT_TAG }}:refs/remotes/origin/{{ GIT_TAG }}'
        update: no
      register: cloned 

    - debug: msg="{{ cloned }}"
    - debug: msg="{{ cloned }}"
      
    - name: Execute the npm install 
      command: npm install
      args:
        chdir: "{{ app_path }}/{{ app_dir }}" 
      register: npm_install

    #- name: Execute the bower install/grunt install 
    #  command: "/home/varanet/.nvm/versions/node/v0.12.7/bin/npm install -g bower grunt-cli"
    #  args:
    #    chdir: "{{ app_path }}/{{ app_dir }}" 
    #  register: npm_install

    #- npm:
    #    path: "{{ app_path }}/{{ app_dir }}"
    #    name: bower
    #    global: no
    
    #- npm:
    #    path: "{{ app_path }}/{{ app_dir }}"
    #    name: grunt
    #    global: no

    #- name: Install packages based on bower.json in  "{{ app_path }}/{{ app_dir }}" 
    #  bower:
    #    path: "{{ app_path }}/{{ app_dir }}"
    #  register: bower_install

    - name: Execute the bower install 
      command: "/home/varanet/.nvm/versions/node/v0.12.7/bin/bower --config.interactive=false --allow-root install"
      args:
        chdir: "{{ app_path }}/{{ app_dir }}" 
      register: bower_install

    - name: Create the build 
      command: "/home/varanet/.nvm/versions/node/v0.12.7/bin/grunt build"
      args:
        chdir: "{{ app_path }}/{{ app_dir }}" 
      register: grunt_build

    - name: PM2 | Install PM2 
      npm: name=pm2 global=yes 
      tags: pm2

    - name: start application with pm2 
      command: pm2 start "{{ app_path }}/{{ app_dir }}/{{ server_file }}" 
      ignore_errors: yes 
      become: yes 
      tags: pm2  

    - name: Print complete log list
      command: git log --pretty=oneline "{{ cloned.msg.after }}..{{ cloned.msg.before }}"
      register: commits_list


    #- name: install nginx
    #  apt: name=nginx state=present
    #  sudo: yes

    #- name: copy nginx.conf to the server
    #  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    #  sudo: yes

    #- name: delete default virtualhost
    #  file: path=/etc/nginx/sites-enabled/default state=absent
    #  sudo: yes

    #- name: add mysite site-available
    #  template: src=mysite.conf.j2 dest=/etc/nginx/sites-available/mysite.conf
    #  sudo: yes

    #- name: link mysite site-enabled
    #  file: path=/etc/nginx/sites-enabled/mysite src=/etc/nginx/sites-available/mysite.conf state=link
    #  sudo: yes


    - mail:
        host: smtp.gmail.com
        port: 465
        username: atul.agrawal@varaunited.com
        password: Atul@9911
        to: Atul Agrawal <atul.agrawal@varaunited.com>
        subject: Deployment Status
        body: 'Your deployment has been successfully done.Commits Deployed List'

    - debug: mag="{{ commits_list }}"
    - debug: msg="{{npm_install.stdout}}"
    - debug: msg="{{npm_install.stderr}}"
    - debug: msg="{{bower_install.stdout}}"
    - debug: msg="{{bower_install.stderr}}"
    - debug: msg="{{pm2_restart.stdout}}"
        







         
        
  